### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by tseemann** [matsengrp/indelible#1]
I was wondering if you were going to make a release with your new refactoring, especially `getopt` support.

**Comment by matsen** [comment]
!!! Hello, Torsten!

I think you can see that this is abandoned. We ended up working on https://github.com/santa-dev/santa-sim instead. 

Feel free to use the code, but by making a release I'd be certifying that this was correct, which I don't feel confident doing. The dev on this has left. I do hope it's useful though.

**Comment by tseemann** [comment]
@matsen no worries - the only reason was that @snacktavish was using `indelible` in her
https://github.com/snacktavish/TreeToReads package and i was trying to package the dependencies.

It's on the backburner now.
